[package]
name = "nostr-flutter-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.5.1"
nostr-sdk = { version = "0.35", default-features = false, features = [
    "all-nips",
] }
